workflow:
  id: feature-derivation
  kind: ceremony
  parent: art
  facilitator: '@release-train-engineer'
  steps:
  - id: derive-business
    kind: author
    actor: '@product-manager'
    output: feature
    conditions:
    - id: parent_epic_present
      kind: postcondition
      type: state
      set_selector:
        set_type: artifact
        artifact_types:
        - alias: feature
          schema_id: feature
        set_query: feature.filter(x, x.id == unit_id)
      set_predicate: selected.all(x, has(x.parent_epic))
    - id: feature_typed_business_or_enabler
      kind: postcondition
      type: state
      set_selector:
        set_type: artifact
        artifact_types:
        - alias: feature
          schema_id: feature
        set_query: feature.filter(x, x.id == unit_id)
      set_predicate: selected.all(x, has(x.type) && (x.type == "business" || x.type
        == "enabler"))
  - id: derive-enabler
    kind: author
    actor: '@system-architect'
    output: feature-enabler
    conditions:
    - id: after_derive_business
      kind: precondition
      type: after
      step_id: derive-business
    - id: parent_epic_present
      kind: postcondition
      type: state
      set_selector:
        set_type: artifact
        artifact_types:
        - alias: feature
          schema_id: feature
        set_query: feature.filter(x, x.id == unit_id)
      set_predicate: selected.all(x, has(x.parent_epic))
    - id: feature_typed_business_or_enabler
      kind: postcondition
      type: state
      set_selector:
        set_type: artifact
        artifact_types:
        - alias: feature
          schema_id: feature
        set_query: feature.filter(x, x.id == unit_id)
      set_predicate: selected.all(x, has(x.type) && (x.type == "business" || x.type
        == "enabler"))
