workflow:
  id: architectural-vision
  kind: practice
  parent: lpm
  facilitator: '@value-management-officier'
  steps:
  - id: ea-draft
    kind: author
    actor: '@enterprise-architect'
    output: architectural-vision
    conditions:
    - id: epic_in_reviewing
      kind: precondition
      type: state
      set_selector:
        set_type: artifact
        artifact_types:
        - alias: epic
          schema_id: epic
        set_query: epic.filter(x, x.id == unit_id)
      set_predicate: selected.all(x, x.status == "reviewing")
  - id: challenge-value
    kind: challenge
    actor: '@business-owner'
    output: value-review
    conditions:
    - id: after_ea_draft
      kind: precondition
      type: after
      step_id: ea-draft
  - id: challenge-security-nfr
    kind: challenge
    actor: '@security-expert'
    output: security-review
    conditions:
    - id: after_ea_draft
      kind: precondition
      type: after
      step_id: ea-draft
  - id: challenge-operability
    kind: challenge
    actor: '@operator'
    output: operability-review
    conditions:
    - id: after_ea_draft
      kind: precondition
      type: after
      step_id: ea-draft
  - id: owner-rewrite
    kind: author
    actor: '@enterprise-architect'
    output: architectural-vision
    conditions:
    - id: after_challenge_value
      kind: precondition
      type: after
      step_id: challenge-value
    - id: after_challenge_security_nfr
      kind: precondition
      type: after
      step_id: challenge-security-nfr
    - id: after_challenge_operability
      kind: precondition
      type: after
      step_id: challenge-operability
  - id: render
    kind: render
    actor: '@enterprise-architect'
    output: architectural-vision
    conditions:
    - id: after_owner_rewrite
      kind: precondition
      type: after
      step_id: owner-rewrite
